//Properties
export const ADD_PROPERTIES = 'ADD_PROPERTIES';
export const ADD_PROPERTIES_SUCCESS = 'ADD_PROPERTIES_SUCCESS';
export const ADD_PROPERTIES_ERROR = 'ADD_PROPERTIES_ERROR';
export const GET_PROPERTIES = 'GET_PROPERTIES';
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTIES_ERROR = 'GET_PROPERTIES_ERROR';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const UPDATE_PROPERTY_SUCCESS = 'UPDATE_PROPERTY_SUCCESS';
export const UPDATE_PROPERTY_ERROR = 'UPDATE_PROPERTY_ERROR';
export const SET_PROPERTY = 'SET_PROPERTY';
export const SET_PROPERTY_SUCCESS = 'SET_PROPERTY_SUCCESS';
export const SET_PROPERTY_ERROR = 'SET_PROPERTY_ERROR';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const DELETE_PROPERTY_ERROR = 'DELETE_PROPERTY_ERROR';
export const DELETE_PROPERTY_SUCCESS = 'DELETE_PROPERTY_SUCCESS';

//Customers
export const ADD_CUSTOMERS = 'ADD_CUSTOMER';
export const ADD_CUSTOMERS_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMERS_ERROR = 'ADD_CUSTOMER_ERROR';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_ERROR = 'GET_CUSTOMERS_ERROR';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_ERROR = 'UPDATE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

//Users
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const ADD_USER_ATTACHMENT = 'ADD_USER_ATTACHMENT';
export const ADD_USER_ATTACHMENT_SUCCESS = 'ADD_USER_ATTACHMENTS_SUCCESS';
export const ADD_USER_ATTACHMENT_ERROR = 'ADD_USER_ATTACHMENTS_ERROR';
export const DELETE_USER_ATTACHMENT = 'DELETE_USER_ATTACHMENTS';
export const DELETE_USER_ATTACHMENT_ERROR = 'DELETE_USER_ATTACHMENTS_ERROR';
export const DELETE_USER_ATTACHMENT_SUCCESS = 'DELETE_USER_ATTACHMENTS_SUCCESS';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE'
export const UPDATE_USER_IMAGE_SUCCESS = 'UPDATE_USER_IMAGE_SUCCESS'
export const UPDATE_USER_IMAGE_ERROR = 'UPDATE_USER_IMAGE_ERROR'

//Roles
export const ADD_ROLE = 'ADD_ROLE';
export const ADD_ROLE_SUCCESS = 'ADD_ROLE_SUCCESS';
export const ADD_ROLE_ERROR = 'ADD_ROLE_ERROR';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_ERROR = 'GET_ROLES_ERROR';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR';
export const DELETE_ROLE = 'DELETE_CUSTOMER';
export const DELETE_ROLE_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_ROLE_ERROR = 'DELETE_CUSTOMER_ERROR';
export const UPDATE_ROLE_PRIORITY = 'UPDATE_ROLE_PRIORITY';
export const UPDATE_ROLE_PRIORITY_SUCCESS = 'UPDATE_ROLE_SUCCESS_PRIORITY';
export const UPDATE_ROLE_PRIORITY_ERROR = 'UPDATE_ROLE_ERROR_PRIORITY';

//Files
export const ADD_FILES = 'ADD_FILES';
export const ADD_FILES_SUCCESS = 'ADD_FILES_SUCCESS';
export const ADD_FILES_ERROR = 'ADD_FILES_ERROR';
export const GET_FILES = 'GET_FILES';
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_ERROR = 'GET_FILES_ERROR';
export const UPDATE_FILE = 'UPDATE_FILE';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const UPDATE_FILE_ERROR = 'UPDATE_FILE_ERROR';
export const DELETE_FILE = 'DELETE_FILE';
export const DELETE_FILE_ERROR = 'DELETE_FILE_ERROR';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';

//Builders
export const ADD_BUILDERS = 'ADD_BUILDERS';
export const ADD_BUILDERS_SUCCESS = 'ADD_BUILDERS_SUCCESS';
export const ADD_BUILDERS_ERROR = 'ADD_BUILDERS_ERROR';
export const GET_BUILDERS = 'GET_BUILDERS';
export const GET_BUILDERS_SUCCESS = 'GET_BUILDERS_SUCCESS';
export const GET_BUILDERS_ERROR = 'GET_BUILDERS_ERROR';
export const UPDATE_BUILDER = 'UPDATE_BUILDER';
export const UPDATE_BUILDER_SUCCESS = 'UPDATE_BUILDER_SUCCESS';
export const UPDATE_BUILDER_ERROR = 'UPDATE_BUILDER_ERROR';
export const DELETE_BUILDER = 'DELETE_BUILDER';
export const DELETE_BUILDER_ERROR = 'DELETE_BUILDER_ERROR';
export const DELETE_BUILDER_SUCCESS = 'DELETE_BUILDER_SUCCESS';

//Categories
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const ADD_CATEGORIES_SUCCESS = 'ADD_CATEGORIES_SUCCESS';
export const ADD_CATEGORIES_ERROR = 'ADD_CATEGORIES_ERROR';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

//Division
export const ADD_DIVISIONS = 'ADD_DIVISIONS';
export const ADD_DIVISIONS_SUCCESS = 'ADD_DIVISIONS_SUCCESS';
export const ADD_DIVISIONS_ERROR = 'ADD_DIVISIONS_ERROR';
export const GET_DIVISIONS = 'GET_DIVISIONS';
export const GET_DIVISIONS_SUCCESS = 'GET_DIVISIONS_SUCCESS';
export const GET_DIVISIONS_ERROR = 'GET_DIVISIONS_ERROR';
export const UPDATE_DIVISION = 'UPDATE_DIVISION';
export const UPDATE_DIVISION_SUCCESS = 'UPDATE_DIVISION_SUCCESS';
export const UPDATE_DIVISION_ERROR = 'UPDATE_DIVISION_ERROR';
export const DELETE_DIVISION = 'DELETE_DIVISION';
export const DELETE_DIVISION_ERROR = 'DELETE_DIVISION_ERROR';
export const DELETE_DIVISION_SUCCESS = 'DELETE_DIVISION_SUCCESS';

//currentUserProcessActions
export const GET_CURRENT_USER_PROCESS_LIST = 'GET_CURRENT_USER_PROCESS_LIST';
export const GET_CURRENT_USER_PROCESS_LIST_SUCCESS = 'GET_CURRENT_USER_PROCESS_LIST_SUCCESS';
export const GET_CURRENT_USER_PROCESS_LIST_ERROR = 'GET_CURRENT_USER_PROCESS_LIST_ERROR';

//Build Models
export const ADD_BUILDMODELS = 'ADD_BUILDMODELS';
export const ADD_BUILDMODELS_SUCCESS = 'ADD_BUILDMODELS_SUCCESS';
export const ADD_BUILDMODELS_ERROR = 'ADD_BUILDMODELS_ERROR';
export const GET_BUILDMODELS = 'GET_BUILDMODELS';
export const GET_BUILDMODELS_SUCCESS = 'GET_BUILDMODELS_SUCCESS';
export const GET_BUILDMODELS_ERROR = 'GET_BUILDMODELS_ERROR';
export const UPDATE_BUILDMODEL = 'UPDATE_BUILDMODEL';
export const UPDATE_BUILDMODEL_SUCCESS = 'UPDATE_BUILDMODEL_SUCCESS';
export const UPDATE_BUILDMODEL_ERROR = 'UPDATE_BUILDMODEL_ERROR';
export const DELETE_BUILDMODEL = 'DELETE_BUILDMODEL';
export const DELETE_BUILDMODEL_ERROR = 'DELETE_BUILDMODEL_ERROR';
export const DELETE_BUILDMODEL_SUCCESS = 'DELETE_BUILDMODEL_SUCCESS';

//Templates

export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const ADD_TEMPLATE_SUCCESS = 'ADD_TEMPLATE_SUCCESS';
export const ADD_TEMPLATE_ERROR = 'ADD_TEMPLATE_ERROR';
export const GET_TEMPLATES = 'GET_TEMPLATES';
export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const GET_TEMPLATES_ERROR = 'GET_TEMPLATES_ERROR';
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE';
export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_ERROR = 'UPDATE_TEMPLATE_ERROR';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_ERROR = 'DELETE_TEMPLATE_ERROR';
export const SET_CURRENT_TEMPLATE = 'SET_CURRENT_TEMPLATE';
export const SET_CURRENT_TEMPLATE_SUCCESS = 'SET_CURRENT_TEMPLATE_SUCCESS';
export const SET_CURRENT_TEMPLATE_ERROR = 'SET_CURRENT_TEMPLATE_ERROR';

//BankCredits
export const ADD_BANK_CREDITS = 'ADD_BANK_CREDITS';
export const ADD_BANK_CREDITS_SUCCESS = 'ADD_BANK_CREDITS_SUCCESS';
export const ADD_BANK_CREDITS_ERROR = 'ADD_BANK_CREDITS_ERROR';
export const GET_BANK_CREDITS = 'GET_BANK_CREDITS';
export const GET_BANK_CREDITS_SUCCESS = 'GET_BANK_CREDITS_SUCCESS';
export const GET_BANK_CREDITS_ERROR = 'GET_BANK_CREDITS_ERROR';
export const UPDATE_BANK_CREDIT = 'UPDATE_BANK_CREDIT';
export const UPDATE_BANK_CREDIT_SUCCESS = 'UPDATE_BANK_CREDIT_SUCCESS';
export const UPDATE_BANK_CREDIT_ERROR = 'UPDATE_BANK_CREDIT_ERROR';
export const DELETE_BANK_CREDIT = 'DELETE_BANK_CREDIT';
export const DELETE_BANK_CREDIT_ERROR = 'DELETE_BANK_CREDIT_ERROR';
export const DELETE_BANK_CREDIT_SUCCESS = 'DELETE_BANK_CREDIT_SUCCESS';

//Timeline
export const GET_TIMELINE = 'GET_TIMELINE';
export const GET_TIMELINE_SUCCESS = 'GET_TIMELINE_SUCCESS';
export const GET_TIMELINE_ERROR = 'GET_TIMELINE_ERROR';

//Articles

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_ERROR = 'ADD_ARTICLE_ERROR';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const SET_CURRENT_ARTICLE_SUCCESS = 'SET_CURRENT_ARTICLE_SUCCESS';
export const SET_CURRENT_ARTICLE_ERROR = 'SET_CURRENT_ARTICLE_ERROR';
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE'
export const PUBLISH_ARTICLE_SUCCESS = 'PUBLISH_ARTICLE_SUCCESS'
export const PUBLISH_ARTICLE_ERROR = 'PUBLISH_ARTICLE_ERROR'

//Banks
export const ADD_BANKS = 'ADD_BANK';
export const ADD_BANKS_SUCCESS = 'ADD_BANK_SUCCESS';
export const ADD_BANKS_ERROR = 'ADD_BANK_ERROR';
export const GET_BANKS = 'GET_BANKS';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_ERROR = 'GET_BANKS_ERROR';
export const UPDATE_BANK = 'UPDATE_BANK';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_ERROR = 'UPDATE_BANK_ERROR';
export const DELETE_BANK = 'DELETE_BANK';
export const DELETE_BANK_ERROR = 'DELETE_BANK_ERROR';
export const DELETE_BANK_SUCCESS = 'DELETE_BANK_SUCCESS';
export const SET_BANK = 'SET_BANK';
export const SET_BANK_ERROR = 'SET_BANK_ERROR';
export const SET_BANK_SUCCESS = 'SET_BANK_SUCCESS';

//Investors
export const ADD_INVESTORS = 'ADD_INVESTOR';
export const ADD_INVESTORS_SUCCESS = 'ADD_INVESTOR_SUCCESS';
export const ADD_INVESTORS_ERROR = 'ADD_INVESTOR_ERROR';
export const GET_INVESTORS = 'GET_INVESTORS';
export const GET_INVESTORS_SUCCESS = 'GET_INVESTORS_SUCCESS';
export const GET_INVESTORS_ERROR = 'GET_INVESTORS_ERROR';
export const UPDATE_INVESTOR = 'UPDATE_INVESTOR';
export const UPDATE_INVESTOR_SUCCESS = 'UPDATE_INVESTOR_SUCCESS';
export const UPDATE_INVESTOR_ERROR = 'UPDATE_INVESTOR_ERROR';
export const DELETE_INVESTOR = 'DELETE_INVESTOR';
export const DELETE_INVESTOR_ERROR = 'DELETE_INVESTOR_ERROR';
export const DELETE_INVESTOR_SUCCESS = 'DELETE_INVESTOR_SUCCESS';
export const SET_INVESTOR = 'SET_INVESTOR';
export const SET_INVESTOR_ERROR = 'SET_INVESTOR_ERROR';
export const SET_INVESTOR_SUCCESS = 'SET_INVESTOR_SUCCESS';